#pragma once

/*! \file
 * \brief Implementation of predefined built-in symbols. 
 */

#include "threadscript/symbol_table.hpp"
#include "threadscript/vm_data.hpp"

namespace threadscript {

//! Namespace for implementation of predefined built-in (C++ native) symbols
/*! This namespace contains predefined function implementation in classes
 * derived from threadscript::basic_value_native_fun. The class names have
 * prefix \c f_ in order to not collide with C++ keywords. It also contains
 * definitions of any predefined variables.
 *
 * Classes in this namespace must be registered in variable \c factory in
 * function add_predef_symbols().
 *
 * Classes in this namespace should be \c final.
 *
 * Declarations in this namespace should be kept in the lexicographical order.
 * \test in file test_predef.cpp */
namespace predef {

//! Implementation of function \c bool.
/*! It must be called with one or two arguments. The last argument is converted
 * to type \c bool and the result is returned. A \c bool value \c false yields
 * \c false. Any other non-null value yields \c true. A \c null causes throwing
 * exception::value_null.
 *
 * If called with two arguments and the first one is of type \c bool, it is
 * reused and the result is stored into it. In any other case, a new value is
 * allocated for the result.
 *
 * It throws exception::op_narg if the number of arguments is not 1 or 2. */
template <impl::allocator A>
class f_bool final: public basic_value_native_fun<f_bool<A>, A> {
    using basic_value_native_fun<f_bool<A>, A>::basic_value_native_fun;
protected:
    typename basic_value<A>::value_ptr eval(basic_state<A>& thread,
                                            basic_symbol_table<A>& l_vars,
                                            const basic_code_node<A>& node,
                                            std::string_view fun_name) override;
    //! Converts a value to basic_value_bool.
    /*! This is a helper function used by eval() and it should be used (for
     * consistency) by any other conversion to \c bool, for example, in f_if.
     * \param[in] thread the current thread
     * \param[in] val the value to be converted
     * \return \c false if \a val is basic_value_bool containing \c false;
     * \c true otherwise
     * \throw exception::value_null if \a val is \c nullptr */
    static bool convert(basic_state<A>& thread,
                        typename basic_value<A>::value_ptr val);
};

//! Implementation of function \c print.
/*! It writes all its arguments atomically to the standard output, which can be
 * redirected to any \c std::ostream by basic_state::std_out or
 * basic_virtual_machine::std_out. A value is written by its member function
 * basic_value::write(). If a value is \c null, then the string \c "null" is
 * written. Output generated by a single call of \c print is not interleaved by
 * other output to the same stream. It returns \c null. */
template <impl::allocator A>
class f_print final: public basic_value_native_fun<f_print<A>, A> {
    using basic_value_native_fun<f_print<A>, A>::basic_value_native_fun;
protected:
    typename basic_value<A>::value_ptr eval(basic_state<A>& thread,
                                            basic_symbol_table<A>& l_vars,
                                            const basic_code_node<A>& node,
                                            std::string_view fun_name) override;
};

//! Implementation of command \c seq.
/*! It evaluates all its arguments sequentially. This is essentially equivalent
 * to a block of commands in other programming languages. It returns \c null. */
template <impl::allocator A>
class f_seq final: public basic_value_native_fun<f_seq<A>, A> {
    using basic_value_native_fun<f_seq<A>, A>::basic_value_native_fun;
protected:
    typename basic_value<A>::value_ptr eval(basic_state<A>& thread,
                                            basic_symbol_table<A>& l_vars,
                                            const basic_code_node<A>& node,
                                            std::string_view fun_name) override;
};

} // namespace predef

//! Creates a new symbol table containing predefined built-in symbols.
/*! \tparam A an allocator type
 * \param[in] alloc the allocator used for creating the symbol table
 * \return a newly creating symbol table containing predefined built-in C++
 * native symbols defined in namespace threadscript::predef. */
template <impl::allocator A>
std::shared_ptr<basic_symbol_table<A>> predef_symbols(const A& alloc);

//! Adds default predefined built-in symbols to a symbol table.
/*! It adds built-in C++ native symbols defined in namespace
 * threadscript::predef into \a sym. It is usually used to initialize a symbol
 * table that will be set as the global shared symbol table
 * basic_virtual_machine::sh_vars. The function does nothing if \a sym is \c
 * nullptr.
 * \tparam A an allocator type
 * \param[in] sym a symbol table
 * \param[in] replace if \c false, any existing symbol with a name equal to
 * a name to be added is left unchanged; if \c true, any such symbol is
 * replaced by the default value.
 * \return \a sym */
template <impl::allocator A> std::shared_ptr<basic_symbol_table<A>>
add_predef_symbols(std::shared_ptr<basic_symbol_table<A>> sym, bool replace);

} // namespace threadscript
